# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    # Inject the named 'transfer' LockFactory into TransferService
    App\Service\TransferService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $lockFactory: '@lock.transfer.factory'
